### ISSUE TITLE
Issue with version parameter

### ISSUE THREAD

**Issue by oveee92** [oveee92/vaulti#7]
When running `vaulti -V` :
```
Traceback (most recent call last):
  File "/home/otislevoll/git/vaulti/.venv/bin/vaulti", line 5, in <module>
    from vaulti_ansible.vaulti import main
  File "/home/otislevoll/git/vaulti/.venv/lib64/python3.12/site-packages/vaulti_ansible/vaulti.py", line 96, in <module>
    from __about__ import __version__
ModuleNotFoundError: No module named '__about__'
```

**Comment by oveee92** [comment]
Fixed in v1.0.5
